import "server-only";
import { createGitHubClient } from "./client";
import type { GeneratedContentRecord, BrandRecord, CycleRecord } from "@/types";

interface CreateHtmlPROptions {
  accessToken: string;
  repoFullName: string;
  targetPath: string;
  content: GeneratedContentRecord;
  brand: BrandRecord;
  cycle: CycleRecord | null;
}

export interface CreateHtmlPRResult {
  pr_url: string;
  branch_name: string;
  file_path: string;
}

function appendContentBlock(existingHtml: string, content: GeneratedContentRecord, cycleNum: number) {
  const block = [
    "",
    "<!-- suppgo:start -->",
    `<section class="suppgo-content-block" data-content-type="${content.content_type}" data-cycle="${cycleNum}">`,
    `  <h2>${content.title ?? "SuppGo Content Update"}</h2>`,
    `  <p>${content.body.replace(/\n+/g, "</p>\n  <p>")}</p>`,
    "</section>",
    "<!-- suppgo:end -->",
    "",
  ].join("\n");

  if (existingHtml.includes("<!-- suppgo:start -->") && existingHtml.includes("<!-- suppgo:end -->")) {
    return existingHtml.replace(
      /<!-- suppgo:start -->[\s\S]*?<!-- suppgo:end -->/m,
      block.trim(),
    );
  }

  if (/<section[^>]*id=["']faq["'][^>]*>/i.test(existingHtml)) {
    return existingHtml.replace(/(<section[^>]*id=["']faq["'][^>]*>)/i, `$1${block}`);
  }

  if (/<\/main>/i.test(existingHtml)) {
    return existingHtml.replace(/<\/main>/i, `${block}\n</main>`);
  }

  if (/<\/body>/i.test(existingHtml)) {
    return existingHtml.replace(/<\/body>/i, `${block}\n</body>`);
  }

  return `${existingHtml}\n${block}`;
}

export async function createHtmlContentPR(options: CreateHtmlPROptions): Promise<CreateHtmlPRResult> {
  const { accessToken, repoFullName, targetPath, content, brand, cycle } = options;
  const octokit = createGitHubClient(accessToken);
  const slashIndex = repoFullName.indexOf("/");

  if (slashIndex === -1) {
    throw new Error(`Invalid repo format: "${repoFullName}". Expected "owner/repo".`);
  }

  const owner = repoFullName.slice(0, slashIndex);
  const repo = repoFullName.slice(slashIndex + 1);
  const cycleNum = cycle?.cycle_number ?? 0;
  const dateSuffix = new Date().toISOString().split("T")[0].replace(/-/g, "");
  const branchName = `suppgo/cycle-${cycleNum}-html-${dateSuffix}`;

  const { data: repoData } = await octokit.repos.get({ owner, repo });
  const defaultBranch = repoData.default_branch;
  const { data: refData } = await octokit.git.getRef({
    owner,
    repo,
    ref: `heads/${defaultBranch}`,
  });
  const baseSha = refData.object.sha;

  try {
    await octokit.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${branchName}`,
      sha: baseSha,
    });
  } catch (err: unknown) {
    const status = (err as { status?: number }).status;
    if (status !== 422) throw err;
  }

  const existingFile = await octokit.repos.getContent({
    owner,
    repo,
    path: targetPath,
    ref: branchName,
  });

  if (Array.isArray(existingFile.data) || existingFile.data.type !== "file") {
    throw new Error(`Expected file target for HTML update but found directory or missing path: ${targetPath}`);
  }

  const existingSha = existingFile.data.sha;
  const existingHtml = Buffer.from(existingFile.data.content, "base64").toString("utf8");
  const updatedHtml = appendContentBlock(existingHtml, content, cycleNum);
  const encoded = Buffer.from(updatedHtml, "utf8").toString("base64");

  await octokit.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: targetPath,
    message: `[SuppGo] Update ${content.content_type.replace(/_/g, " ")} in ${targetPath} — cycle ${cycleNum}`,
    content: encoded,
    branch: branchName,
    sha: existingSha,
  });

  const prBody = [
    `## SuppGo Content — Cycle ${cycleNum}`,
    "",
    `**Content type:** ${content.content_type.replace(/_/g, " ")}`,
    `**Brand:** ${brand.brand_name}`,
    `**File:** \`${targetPath}\``,
    "",
    "### Update strategy",
    "In-place HTML update based on repository analysis. SuppGo inserted or refreshed a managed content block in the detected target file.",
    "",
    "_Generated by [SuppGo](https://suppgo.com). Review and edit as needed, then merge to go live._",
  ].join("\n");

  let prUrl: string;
  try {
    const { data: prData } = await octokit.pulls.create({
      owner,
      repo,
      title: `[SuppGo] ${content.title ?? content.content_type} — Cycle ${cycleNum}`,
      head: branchName,
      base: defaultBranch,
      body: prBody,
    });
    prUrl = prData.html_url;
  } catch (err: unknown) {
    const status = (err as { status?: number }).status;
    if (status === 422) {
      const { data: prs } = await octokit.pulls.list({
        owner,
        repo,
        head: `${owner}:${branchName}`,
        state: "open",
      });
      if (prs.length === 0) throw err;
      prUrl = prs[0].html_url;
    } else {
      throw err;
    }
  }

  return { pr_url: prUrl, branch_name: branchName, file_path: targetPath };
}
