import "server-only";
import { createGitHubClient } from "./client";
import { formatContentAsMarkdown } from "./content-formatter";
import type { GeneratedContentRecord, BrandRecord, CycleRecord } from "@/types";

interface CreatePROptions {
  accessToken: string;
  repoFullName: string; // "owner/repo"
  contentDir: string; // e.g. "content/pages"
  content: GeneratedContentRecord;
  brand: BrandRecord;
  cycle: CycleRecord | null;
}

export interface CreatePRResult {
  pr_url: string;
  branch_name: string;
  file_path: string;
}

export async function createContentPR(options: CreatePROptions): Promise<CreatePRResult> {
  const { accessToken, repoFullName, contentDir, content, brand, cycle } = options;
  const octokit = createGitHubClient(accessToken);

  const slashIndex = repoFullName.indexOf("/");
  if (slashIndex === -1) {
    throw new Error(`Invalid repo format: "${repoFullName}". Expected "owner/repo".`);
  }
  const owner = repoFullName.slice(0, slashIndex);
  const repo = repoFullName.slice(slashIndex + 1);

  const cycleNum = cycle?.cycle_number ?? 0;
  const dateSuffix = new Date().toISOString().split("T")[0].replace(/-/g, "");
  const branchName = `suppgo/cycle-${cycleNum}-content-${dateSuffix}`;

  const { filename, body } = formatContentAsMarkdown(content, brand, cycle);
  const normalizedDir = contentDir.trim() === "." ? "" : contentDir.replace(/\/$/, "").replace(/^\//, "");
  const filePath = normalizedDir ? `${normalizedDir}/${filename}` : filename;

  // Resolve the default branch and its HEAD sha
  const { data: repoData } = await octokit.repos.get({ owner, repo });
  const defaultBranch = repoData.default_branch;

  const { data: refData } = await octokit.git.getRef({
    owner,
    repo,
    ref: `heads/${defaultBranch}`,
  });
  const baseSha = refData.object.sha;

  // Create feature branch — ignore 422 if branch already exists from a prior run today
  try {
    await octokit.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${branchName}`,
      sha: baseSha,
    });
  } catch (err: unknown) {
    const status = (err as { status?: number }).status;
    if (status !== 422) throw err;
    // Branch already exists — reuse it
  }

  // Commit the file
  const fileContent = Buffer.from(body, "utf8").toString("base64");
  const commitMessage = `[SuppGo] Add ${content.content_type.replace(/_/g, " ")} — cycle ${cycleNum}`;

  // Check if file already exists so we can update rather than create
  let existingSha: string | undefined;
  try {
    const { data: existing } = await octokit.repos.getContent({ owner, repo, path: filePath, ref: branchName });
    if (!Array.isArray(existing) && existing.type === "file") {
      existingSha = existing.sha;
    }
  } catch {
    // File does not exist — fine, we'll create it
  }

  await octokit.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: filePath,
    message: commitMessage,
    content: fileContent,
    branch: branchName,
    ...(existingSha ? { sha: existingSha } : {}),
  });

  // Build PR body
  const promptBullets =
    content.target_prompts.length > 0
      ? content.target_prompts.map((p) => `- ${p}`).join("\n")
      : "_No specific prompts targeted._";

  const prBody = [
    `## SuppGo Content — Cycle ${cycleNum}`,
    "",
    `**Content type:** ${content.content_type.replace(/_/g, " ")}`,
    `**Brand:** ${brand.brand_name}`,
    `**File:** \`${filePath}\``,
    "",
    "### Target prompts",
    promptBullets,
    "",
    "### Expected visibility impact",
    "Merging this content should increase the brand mention rate for the targeted prompt categories in the next SuppGo cycle.",
    "",
    "_Generated by [SuppGo](https://suppgo.com). Review and edit as needed, then merge to go live._",
  ].join("\n");

  // Open PR — ignore 422 if a PR already exists for this branch
  let prUrl: string;
  try {
    const { data: prData } = await octokit.pulls.create({
      owner,
      repo,
      title: `[SuppGo] ${content.title ?? content.content_type} — Cycle ${cycleNum}`,
      head: branchName,
      base: defaultBranch,
      body: prBody,
    });
    prUrl = prData.html_url;
  } catch (err: unknown) {
    const status = (err as { status?: number }).status;
    if (status === 422) {
      // PR already open — find it
      const { data: prs } = await octokit.pulls.list({
        owner,
        repo,
        head: `${owner}:${branchName}`,
        state: "open",
      });
      if (prs.length === 0) throw err;
      prUrl = prs[0].html_url;
    } else {
      throw err;
    }
  }

  return { pr_url: prUrl, branch_name: branchName, file_path: filePath };
}
