export const WELL_KNOWN_CONSUMER_HEALTH_BRANDS = [
  "AG1",
  "Athletic Greens",
  "Amazing Grass",
  "Garden of Life",
  "Organifi",
  "Vibrant Health",
  "Bloom",
  "Live it Up",
  "Groove",
  "Nested Naturals",
  "Primal Harvest",
  "Amazing Grass Green Superfood",
  "Green Vibrance",
  "Supergut",
  "Huel",
  "Ka'Chava",
  "Your Super",
  "Ora Organic",
  "Vital All-In-One",
  "BPN",
  "Optimum Nutrition",
  "Dymatize",
  "Isopure",
  "Legion",
  "Transparent Labs",
  "Ghost",
  "PEScience",
  "Ascent",
  "Orgain",
  "Kaged",
  "MuscleTech",
  "Rule One",
  "Cellucor",
  "Pro Jym",
  "Thorne",
  "Momentous",
  "Klean Athlete",
  "Gainful",
  "Promix",
  "Jocko Fuel",
  "Axe & Sledge",
  "Nutricost",
  "Myprotein",
  "EVLution Nutrition",
  "NOW Sports",
  "Onnit",
  "Alpha Brain",
  "Qualia",
  "Mind Lab Pro",
  "Thesis",
  "Neuriva",
  "NooCube",
  "HVMN",
  "Genius Consciousness",
  "Genius Brand",
  "Bulletproof",
  "Four Sigmatic",
  "Natural Stacks",
  "Nootropics Depot",
  "Life Extension",
  "Jarrow Formulas",
  "Pure Encapsulations",
  "Nordic Naturals",
  "Ritual",
  "Care/of",
  "HUM Nutrition",
  "Olly",
  "MegaFood",
  "MaryRuth Organics",
  "Nature Made",
  "Nature's Bounty",
  "Naturelo",
  "Solaray",
  "New Chapter",
  "Solgar",
  "Rainbow Light",
  "SmartyPants",
  "Trace Minerals",
  "Ancient Nutrition",
  "Codeage",
  "Seeking Health",
  "Doctor's Best",
  "Source Naturals",
  "Swanson",
  "Garden of Wisdom",
  "NOW Foods",
  "Garden of Life mykind",
  "Moon Juice",
  "Apothekary",
  "Gaia Herbs",
  "Host Defense",
  "Sun Potion",
  "Organic Olivia",
  "Anima Mundi",
  "WishGarden Herbs",
  "Herbalogic",
  "The Nue Co",
  "Seed",
  "Pendulum",
  "Just Thrive",
  "Culturelle",
  "Align",
  "Florastor",
  "BiomeMD",
  "Digestive Advantage",
  "Hyperbiotics",
  "Renew Life",
  "Ora",
  "BioGaia",
  "BioOptimizers",
  "Ritual Synbiotic+",
  "Pendulum Glucose Control",
  "Beam",
  "Momentous Sleep",
  "Calm",
  "Natural Vitality",
  "Lifeforce",
  "Som Sleep",
  "Remrise",
  "Unisom",
  "Natrol",
  "Zhou Nutrition",
  "MagTech",
  "Moonbrew",
  "Somnee",
  "MUD\\WTR",
  "Vital Proteins",
  "Further Food",
  "Ancient Nutrition Collagen",
  "Great Lakes Wellness",
  "Youtheory",
  "NeoCell",
  "BUBS Naturals",
  "Skinade",
  "Naked Nutrition",
  "Dr. Axe",
  "Nutrafol",
  "Moon Juice SuperHair",
  "Viviscal",
  "Perelel",
  "Needed",
  "Pink Stork",
  "Eu Natural",
  "The Honey Pot",
  "Rael",
  "Mira",
  "Semaine",
  "Bonafide",
  "Womaness",
  "LOLA",
  "Bear Balanced",
  "Hers",
  "Roman",
  "Hims",
  "Test Boost Max",
  "Nugenix",
  "Gorilla Mind",
  "MitoQ",
  "Timeline",
  "Elysium",
  "ProHealth Longevity",
  "Wonderfeel",
  "DoNotAge",
  "Tru Niagen",
  "Renue By Science",
  "Veracity Selfcare",
  "ProtoCol",
  "LMNT",
  "Liquid I.V.",
  "DripDrop",
  "Cure Hydration",
  "Ultima",
  "Needed Hydration",
  "Gainful Hydration",
  "BelliWelli",
  "Hilma",
  "Lemme",
  "Sakara",
  "Arrae",
  "WelleCo",
  "Unbloat",
  "Happy Mammoth",
  "Gundry MD",
  "1st Phorm",
  "MTS Nutrition",
  "Innermost",
  "Codeage Liposomal",
  "One A Day",
  "Centrum",
  "Olly Sleep",
  "Moon Juice Magnesi-Om",
  "Puori",
  "Cymbiotika",
  "Beekeeper's Naturals",
  "Troscriptions",
  "Double Wood Supplements",
  "Liftmode",
  "Health Via Modern Nutrition",
  "Prolon",
  "Lumen",
  "RSP Nutrition",
  "Clean Simple Eats",
  "BelliBaby",
  "Eight Sleep",
  "Bon Charge",
  "Amino Asylum",
  "Vitali Skin Care",
  "Revision Skincare",
  "SkinMedica",
  "The Ordinary",
  "Paula's Choice",
  "Drunk Elephant",
  "Alastin",
  "DefenAge",
  "Stratia",
  "Niche Beauty Lab",
  "OneSkin",
  "HUM Daily Cleanse",
  "Ritual Essential Protein",
  "Live Conscious",
  "Micro Ingredients",
] as const;
